### ISSUE TITLE
[US]: Visualiser liste produits

### ISSUE THREAD

**Issue by MASTTTTT** [IUT-Blagnac/sae-3-01-devapp-2024-2025-G2A-9#18]
### User Story

En tant que client, je veux visualiser la liste des bateaux disponibles afin d'effectuer ma recherche selon mes critères

### Importance

Must (Default)

### Critères d'acceptation

Le client peut voir la liste de produits correspondant à la recherche

### Tâches associées

- [x] #17

**Comment by Perceval00731** [comment]
l'utilisateur peut chercher un produit en fonction de son prix, de sa taille et du type d'énergie qu'il utilise
on sélectionnera aussi les produits faisant 5m de plus ou de moins que la taille demandée et les bateaux qui sont 15% au dessus ou en dessous de la fourchette de prix de l'utilisateur
